addons:
  apt:
    packages:
      - google-chrome-stable
after_success:
  - < coverage/lcov.info "$(yarn bin)"/coveralls
before_script:
  - >-
    ([ -f "$(git rev-parse --git-dir)"/shallow ] && git fetch --unshallow) ||
    true
  - '"$(yarn bin)"/commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT"'
  - '"$(yarn bin)"/commitlint --from="$TRAVIS_COMMIT"'
cache: yarn
dist: trusty
env:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
language: node_js
node_js:
  - '8'
script:
  - make clean && yarn test
  - if test -n "$(git status --porcelain)"; then echo 'Working tree is dirty' && exit 1; fi
sudo: required
