dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
before_install:
- 'npm prune'
before_script:
- '([ -f "$(git rev-parse --git-dir)"/shallow ] && git fetch --unshallow) || true'
- '"$(npm bin)"/commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT"'
- '"$(npm bin)"/commitlint --from="$TRAVIS_COMMIT"'
script:
- 'npm test'
after_success:
- '< coverage/lcov.info "$(npm bin)"/coveralls'
env:
- DBUS_SESSION_BUS_ADDRESS=/dev/null
