title: PageObjectJS
description: Readable. Stable. Maintainable. E2E testing using any browser automation framework.
url: https://pageobject.js.org/
theme: jekyll-theme-minimal
show_downloads: false
include:
- _pageobject_.pageobject.html
- _pageobject_.adapter.html
- _pageobject_.componentclass.html
- _pageobject_.options.html
