title: PageObjectJS
description: Readable. Stable. Maintainable. E2E testing using the Page Object pattern.
url: https://pageobject.js.org/
theme: jekyll-theme-minimal
show_downloads: false
include:
- _index_.pageobject.html
- _index_.componentclass.html
- _index_.options.html
